#!/bin/bash
# Master Script for electrode localization
#
# USAGE: sh /projects/b1134/tools/electrode_modeling/Create_Mgrid.sh SubjectID
#
# BEFORE YOU RUN THIS SCRIPT
# The patient must already have a freesurfer directory generated by recon-all
#
# If this is a Brainstorm patient, and electrodes have already been localized
# export the following files files from brainstorm then run this entire script
# CT image: /projects/b1134/raw/bids/BNI/sub-SUB/ses-PACS/ct/Brainstorm_CT.nii
# Electrode coordinates: /projects/b1134/processed/fs/SUB/SUB/elec_recon/SUB_brainstorm_RAS.txt
#
# Otherwise, if this is not a brainstorm patient, and electrodes have not yet
# been localized, run the ct2mri.sh command in this script, then manually
# localize electrodes in bioimagesuite
#
# Created by Chris Cyr, Braga Lab, February 2024
################################################
module purge
module load fsl
module load matlab/r2020b
module load freesurfer
source $FREESURFER_HOME/SetUpFreeSurfer.sh
SubjectID=$1
SUBJECTS_DIR=/projects/b1134/processed/fs/$SubjectID
ELECRECON_DIR=${SUBJECTS_DIR}/$SubjectID/elec_recon
RAW_DIR=/projects/b1134/raw/bids/BNI/sub-${SubjectID}/ses-PACS

#register Brainstorm CT to Freesurfer T1
gzip ${RAW_DIR}/ct/Brainstorm_CT.nii
sh /projects/b1134/tools/iELVis/ct2mri.sh $SubjectID ${RAW_DIR}/ct/Brainstorm_CT.nii.gz

#convert Brainstorm electrode coordintes from RAS to voxel
matlab -batch "addpath('/projects/b1134/tools/electrode_modeling');Convert_BrainStorm_Coords('$SubjectID')"

#convert from Brainstorm voxel coordinates to Freesurfer voxel coordinates
img2imgcoord -src ${ELECRECON_DIR}/postimpRaw.nii.gz -dest ${ELECRECON_DIR}/postInPre.nii.gz -xfm ${ELECRECON_DIR}/ct2t1.mat ${ELECRECON_DIR}/${SubjectID}_brainstorm_VOX.txt > ${ELECRECON_DIR}/${SubjectID}_freesurfer_VOX.txt

#convert from Freesurfer voxel coordinates to Freesurfer RAS coordinates, create mgrid file,
matlab -batch "addpath('/projects/b1134/tools/electrode_modeling');Create_Mgrid('$SubjectID')"

echo "Please touch up electrodes in Bioimage Suite"
echo "To open Bioimage Suite, enter the following into the command line:"
echo "cd /projects/b1134/processed/fs/$SubjectID/$SubjectID/elec_recon"
echo "/projects/b1134/tools/BioimageSuite/bioimagesuite35/start_bioimagesuite"
echo "Once in Bioimage Suite, load postInPre.nii.gz in the Electrode Editor Window, and $SubjectID.mgrid in the Electrode Control Window"



